baseURL = "https://kimai07.github.io/"
languageCode = "ja"
title = "きまいボックス"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section", "404"]

[author]
    name = "Kenji Imai"

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "Profile"
    url = "/profile/"
    weight = 10
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/kimai07"
    weight = 20
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/kimai07"
    weight = 30
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/kenji-imai-87a74741/"
    weight = 40

[params]
    mainSections = ["post"]

    description = "Welcome!"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "ki.png"
    width = 50
    height = 50
    alt = "Logo"

    [params.icon]
    url = "favicon.ico"
